###############################
### Stanford Robotics Center
## Container Cookbook 
# mattvc@stanford.edu
###############################

services:
###############################
## Open OpenSai   
###############################

  redis_server:
    image: stanfordroboticscenter/sai
    build:
      context: ./
      dockerfile: docker/Dockerfile.sai
    network_mode: host
    command: redis-server

  OpenSai:
    image: stanfordroboticscenter/sai
    build:
      context: ./
      dockerfile: docker/Dockerfile.sai
    environment:
        - DISPLAY
        - QT_X11_NO_MITSHM=1
    volumes:
      - ./config_folder:/config_folder
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "$HOME/.Xauthority:/root/.Xauthority:rw"
    depends_on:
      - redis_server
    network_mode: host
    privileged: true
    command: sh /OpenSai/scripts/launch.sh
